hv_news_listnews:
    path: /
    defaults:
        _controller: HVNewsBundle:News:index

hv_news_currentevents:
    path: /view/{id}
    defaults:
        _controller: HVNewsBundle:News:viewCurrentEvents
    requirements:
        id: \d+

hv_news_createNew:
    path: /createNew
    defaults:
      _controller: HVNewsBundle:News:createNew

hv_news_editNew:
    path: /editNew
    defaults:
      _controller: HVNewsBundle:News:editNew

hv_news_deleteNew:
    path: /delete
    defaults:
      _controller: HVNewsBundle:News:deleteNew
