hv_news_listnews:
    path: /
    defaults:
        _controller: HVNewsBundle:News:index

hv_news_currentevents:
    path: /view/{id}
    defaults:
        _controller: HVNewsBundle:News:viewCurrentEvents
    requirements:
        id: \d+

hv_news_createNew:
    path: /createNew
    defaults:
      _controller: HVNewsBundle:News:createNew

hv_news_editNew:
    path: /editNew
    defaults:
      _controller: HVNewsBundle:News:editNew

hv_news_deleteNew:
    path: /delete
    defaults:
      _controller: HVNewsBundle:News:deleteNew

hv_news_adminComment:
    path: /adminComment
    defaults:
      _controller: HVNewsBundle:News:adminComment

hv_news_deleteComment:
    path: /deleteComment
    defaults:
      _controller: HVNewsBundle:News:deleteComment

hv_news_editComment:
    path: /editComment
    defaults:
      _controller: HVNewsBundle:News:editComment
