hv_users:
    resource: "@HVUsersBundle/Resources/config/routing.yml"
    prefix:   /users

hv_home:
    resource: "@HVHomeBundle/Resources/config/routing.yml"
    prefix:   /

hv_news:
    resource: "@HVNewsBundle/Resources/config/routing.yml"
    prefix:   /news
