hv_forum_homepage:
    path:     /
    defaults:
      _controller: HVForumBundle:Forum:index

hv_forum_section:
    path:     /{url}
    defaults:
        _controller: HVForumBundle:Forum:viewSection

hv_forum_topic:
    path:     /{url}/topic={id}/{page}
    defaults:
        _controller: HVForumBundle:Forum:viewTopic
        page: 1
    requirements:
        id: \d+
        page: \d+
