hv_forum_homepage:
    path:     /
    defaults:
      _controller: HVForumBundle:Forum:index

hv_forum_section:
    path:     /{url}
    defaults:
        _controller: HVForumBundle:Forum:viewSection

hv_forum_topic:
    path:     /{url}/topic={id}/{page}
    defaults:
        _controller: HVForumBundle:Forum:viewTopic
        page: 1
    requirements:
        id: \d+
        page: \d+

hv_forum_topic_add:
    path:     /{url}/createtopic
    defaults:
        _controller: HVForumBundle:Forum:createTopic

hv_forum_post_add:
    path:     /{url}/topic={id}/addpost
    defaults:
        _controller: HVForumBundle:Forum:addPost
    requirements:
        id: \d+

hv_forum_post_edit:
    path:     /{url}/topic={id}/edit/{idPost}
    defaults:
        _controller: HVForumBundle:Forum:editPost
    requirements:
        id: \d+
        idPost: \d+

hv_forum_post_delete:
    path:     /{url}/topic={id}/delete/{idPost}
    defaults:
        _controller: HVForumBundle:Forum:deletePost
    requirements:
        id: \d+
        idPost: \d+

hv_forum_category_create:
    path: /category/create
    defaults:
      _controller: HVForumBundle:Forum:createCategory

hv_forum_category_delete:
    path: /category/delete
    defaults:
      _controller: HVForumBundle:Forum:deleteCategory

hv_forum_category_edit:
    path: /category/edit
    defaults:
      _controller: HVForumBundle:Forum:editCategory

hv_forum_section_create:
    path: /section/create
    defaults:
      _controller: HVForumBundle:Forum:createSection

hv_forum_section_delete:
    path: /section/delete
    defaults:
      _controller: HVForumBundle:Forum:deleteSection

hv_forum_section_edit:
    path: /section/edit
    defaults:
      _controller: HVForumBundle:Forum:editSection
