<?php

namespace HV\ForumBundle\Repository;

/**
 * ForumTopicViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumTopicViewRepository extends \Doctrine\ORM\EntityRepository
{
  public function getTopicView($idUsers, $idTopic)
  {
    $qb= $this->createQueryBuilder('ftv');
    $qb->where('ftv.users = :idUsers');
    $qb->andWhere('ftv.forumTopic = :idTopic');
    $qb->setParameter('idUsers', $idUsers);
    $qb->setParameter('idTopic', $idTopic);
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
