<?php

namespace HV\ForumBundle\Repository;

/**
 * ForumSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumSectionRepository extends \Doctrine\ORM\EntityRepository
{

}
