<?php

namespace HV\ForumBundle\Repository;

/**
 * ForumTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumTopicRepository extends \Doctrine\ORM\EntityRepository
{
}
