<?php

namespace HV\UsersBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
  public function getConnection(array $postConnection)
  {
    $email = $postConnection['email'];
    $password = $postConnection['password'];

    $users = $this->findOneBy(array(
      'email' => $email
    ));

    if ($users != null) {
      $passHash = $users->getPassword();
      if (password_verify($password, $passHash)) {
        $connection = $users;
      } else {
        $connection = false;
      }
      return $connection;
    }
    return false;
  }
}
